
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 12.4 EDK_MS4.81d
* DO NOT EDIT.
*
* Copyright (c) 1995-2010 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_GRAPHICS_GPIO_DEVICE_ID,
		XPAR_GRAPHICS_GPIO_BASEADDR,
		XPAR_GRAPHICS_GPIO_INTERRUPT_PRESENT,
		XPAR_GRAPHICS_GPIO_IS_DUAL
	},
	{
		XPAR_JOYSTICK_GPIO_DEVICE_ID,
		XPAR_JOYSTICK_GPIO_BASEADDR,
		XPAR_JOYSTICK_GPIO_INTERRUPT_PRESENT,
		XPAR_JOYSTICK_GPIO_IS_DUAL
	}
};


